In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import sys
from pathlib import Path
project_folder = Path.cwd().parent.parent
sys.path.append(str(project_folder))
from modeling.utilities.utils_buoy_data import read_buoy_texts, collapse_to_daily, create_buoy_cols

In [2]:
buoy_data = 'https://www.ndbc.noaa.gov/data/realtime2/LJAC1.txt'

In [3]:
df = read_buoy_texts(buoy_data)

In [4]:
df.dtypes

YY      int64
MM      int64
DD      int64
hh      int64
mm      int64
WDIR      str
WSPD      str
GST       str
WVHT      str
DPD       str
APD       str
MWD       str
PRES      str
ATMP      str
WTMP      str
DEWP      str
VIS       str
PTDY      str
TIDE      str
dtype: object

In [5]:
buoy_df = create_buoy_cols(df)
buoy_df.head(2)

        date  hh   WDIR  WSPD
0 2026-07-29  13  180.0   2.1
1 2026-07-29  13  160.0   1.5

In [6]:
buoy_df.dtypes

date    datetime64[us]
hh               int64
WDIR           float64
WSPD           float64
dtype: object

In [7]:
daily_df = collapse_to_daily(buoy_df)

In [8]:
daily_df

         date      WSPD        WDIR
0  2026-06-14  3.057083  308.625000
1  2026-06-15  3.243333  321.166667
2  2026-06-16  3.125523  316.192469
3  2026-06-17  2.839241  283.628692
4  2026-06-18  2.455357  248.616071
5  2026-06-19  2.877500  279.000000
6  2026-06-20  3.446383  297.234043
7  2026-06-21  3.031760  286.051502
8  2026-06-22  2.660086  283.218884
9  2026-06-23  2.090741  259.907407
10 2026-06-24  2.092174  284.086957
11 2026-06-25  2.664192  272.227074
12 2026-06-26  2.338075  268.870293
13 2026-06-27  2.126289  233.247423
14 2026-06-28  3.836250  236.708333
15 2026-06-29  2.888288  198.918919
16 2026-06-30  3.071930  219.210526
17 2026-07-01  2.399149  236.255319
18 2026-07-02  2.303540  263.451327
19 2026-07-03  3.014224  302.413793
20 2026-07-04  2.414706  268.571429
21 2026-07-05  2.717227  290.924370
22 2026-07-06  3.016318  305.104603
23 2026-07-07  2.628992  301.806723
24 2026-07-08  2.238863  259.099526
25 2026-07-09  2.914602  221.504425
26 2026-07-10  2.869397  221.120690
27 2026-07-11  2.707759  209.008621
28 2026-07-12  1.961304  227.826087
29 2026-07-13  1.941256  264.304933
30 2026-07-14  3.084583  282.708333
31 2026-07-15  1.459135  272.067308
32 2026-07-16  3.546218  186.638655
33 2026-07-17  3.292029  175.217391
34 2026-07-18  2.705714  272.142857
35 2026-07-19  1.944828  272.284483
36 2026-07-20  1.523767  240.582960
37 2026-07-21  1.934498  219.781659
38 2026-07-22  3.743333  324.916667
39 2026-07-23  1.993860  276.710526
40 2026-07-24  2.183028  252.752294
41 2026-07-25  3.224464  206.094421
42 2026-07-26  2.689316  229.230769
43 2026-07-27  1.964126  255.605381
44 2026-07-28  2.410526  216.140351
45 2026-07-29  2.361765  195.735294